//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/TumblerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TumblerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TumblerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TumblerInput"",
    ""maps"": [
        {
            ""name"": ""Tumbler"",
            ""id"": ""ae0a52b3-1867-4b30-ab87-78ab61ab0c2a"",
            ""actions"": [
                {
                    ""name"": ""Flip Car"",
                    ""type"": ""Button"",
                    ""id"": ""f64e6d68-8480-43b8-bc5d-9aa4e73bc47d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset Car"",
                    ""type"": ""Button"",
                    ""id"": ""2ad2351d-a43c-45c2-a898-68adcd219d84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Value"",
                    ""id"": ""ff05be07-f670-4087-916d-77a24909125a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ecf621e7-e41d-4a81-bb79-0f990ca451b9"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flip Car"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bfb5dd7-b55a-4a91-a44b-28083c8ed9b1"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset Car"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2226d9af-73e3-4595-8d0d-181295cf3715"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Tumbler
        m_Tumbler = asset.FindActionMap("Tumbler", throwIfNotFound: true);
        m_Tumbler_FlipCar = m_Tumbler.FindAction("Flip Car", throwIfNotFound: true);
        m_Tumbler_ResetCar = m_Tumbler.FindAction("Reset Car", throwIfNotFound: true);
        m_Tumbler_Boost = m_Tumbler.FindAction("Boost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tumbler
    private readonly InputActionMap m_Tumbler;
    private List<ITumblerActions> m_TumblerActionsCallbackInterfaces = new List<ITumblerActions>();
    private readonly InputAction m_Tumbler_FlipCar;
    private readonly InputAction m_Tumbler_ResetCar;
    private readonly InputAction m_Tumbler_Boost;
    public struct TumblerActions
    {
        private @TumblerInput m_Wrapper;
        public TumblerActions(@TumblerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FlipCar => m_Wrapper.m_Tumbler_FlipCar;
        public InputAction @ResetCar => m_Wrapper.m_Tumbler_ResetCar;
        public InputAction @Boost => m_Wrapper.m_Tumbler_Boost;
        public InputActionMap Get() { return m_Wrapper.m_Tumbler; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TumblerActions set) { return set.Get(); }
        public void AddCallbacks(ITumblerActions instance)
        {
            if (instance == null || m_Wrapper.m_TumblerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TumblerActionsCallbackInterfaces.Add(instance);
            @FlipCar.started += instance.OnFlipCar;
            @FlipCar.performed += instance.OnFlipCar;
            @FlipCar.canceled += instance.OnFlipCar;
            @ResetCar.started += instance.OnResetCar;
            @ResetCar.performed += instance.OnResetCar;
            @ResetCar.canceled += instance.OnResetCar;
            @Boost.started += instance.OnBoost;
            @Boost.performed += instance.OnBoost;
            @Boost.canceled += instance.OnBoost;
        }

        private void UnregisterCallbacks(ITumblerActions instance)
        {
            @FlipCar.started -= instance.OnFlipCar;
            @FlipCar.performed -= instance.OnFlipCar;
            @FlipCar.canceled -= instance.OnFlipCar;
            @ResetCar.started -= instance.OnResetCar;
            @ResetCar.performed -= instance.OnResetCar;
            @ResetCar.canceled -= instance.OnResetCar;
            @Boost.started -= instance.OnBoost;
            @Boost.performed -= instance.OnBoost;
            @Boost.canceled -= instance.OnBoost;
        }

        public void RemoveCallbacks(ITumblerActions instance)
        {
            if (m_Wrapper.m_TumblerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITumblerActions instance)
        {
            foreach (var item in m_Wrapper.m_TumblerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TumblerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TumblerActions @Tumbler => new TumblerActions(this);
    public interface ITumblerActions
    {
        void OnFlipCar(InputAction.CallbackContext context);
        void OnResetCar(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
    }
}
